### PR TITLE
fix: prevent persistent vertical scrollbar

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Review by DSchau — APPROVED** [review]

**Comment by DSchau** [comment]
Deploy preview for *gatsby-blog-starter-kit* ready!

Built with commit ff3353fb58aa436d15f64e7f06db33ecd065be5a

https://deploy-preview-31--gatsby-blog-starter-kit.netlify.com

**Comment by DSchau** [comment]
I can't really replicate a persistent vertical scrollbar. Any examples or reproduction?

**Comment by DanielRuf** [comment]
Sure, open the index page on Windows or any other client where the scrollbar does not get hidden.

overflow-y:scroll and auto are two totally different things.

I'll send you a screenshot from a Browserstack instance later.

**Comment by DanielRuf** [comment]
The empty scrollbar is always there unless we remove the forced scrollbar by removing `overflow-y: scroll`.

`overflow-y: scroll` forces always showing the scrollbar.

bildschirmfoto 2018-07-09 um 09 16 29
bildschirmfoto 2018-07-09 um 09 16 16
bildschirmfoto 2018-07-09 um 09 15 36

**Comment by DanielRuf** [comment]
To be exact, we can remove it as `visible`/ `auto` is the default.

**Comment by DSchau** [comment]
I know the difference between `overflow`s, but it's hard to debug cross-browser/cross-platform idiosyncrasies :) I also recall some of this code being shared in an official Gatsby starter, so that's kind of legacy cruft that I left largely as-is.

That said, thanks for doing the due diligence and in particular for the screenshots. This looks good, I'll merge.

**Pull request merged**
