### PR TITLE
chore: fix name

### PR DESCRIPTION
**Pull request by DSchau**

### CODE REVIEW

**Comment by DSchau** [comment]
Deploy preview for *gatsby-blog-starter-kit* ready!

Built with commit 8d0eb00e48815fb47fef0468166035461dd2f41f

https://deploy-preview-34--gatsby-blog-starter-kit.netlify.com

**Comment by DanielRuf** [comment]
Ah ok, so there was another regression in the past? I guess I oversaw this. But still puzzling that the PR was green.

**Comment by DSchau** [comment]
It can be confusing! Basically a non-master push doesn't trigger that code path 😅

Would you like contributor access? I'd love your assistance!

**Comment by DSchau** [comment]
@DanielRuf made you a contributor! Thanks for your help recently :)

**Comment by DanielRuf** [comment]
> It can be confusing! Basically a non-master push doesn't trigger that code path 😅
True, probably oversaw it in the Travis CI config ;-)

> Would you like contributor access? I'd love your assistance!

I guess I am always willing to help to create better software and solutions together.

**Pull request merged**
